export enum StorageKeys {
  ACCESS_TOKEN = 'access_token',
  REFRESH_TOKEN = 'refresh_token',
  RECENT_ZIP_LIST = 'recent_zip_list',
  USER_CACHED_ZIP = 'user_cached_zip',
  SHOW_PERMISSION_ALERT = 'show_permission_alert',
  USER_CACHED_LOCATION = 'user_cached_location',
  USER_CACHED_STATE = 'user_cached_state',
  USER_CACHED_PHONE_CREDENTIALS = 'user_cached_phone_credentials',
  USER_SELECTED_ZIP_CODE = 'user_selected_zip_code',
  AUTHENTIC_TOKEN = 'authentic_token',
  AUTHENTIC_TOKEN_REDEEMED = 'authentic_token_redeemed',
  FCM_TOKEN = 'fcm_token',
  USER_REGION = 'user_region',
  USER_NAME_CACHE_DATE = 'user_name_cache_date',
  USER_PHONE_NUMBER_CACHE_DATE = 'user_phone_number_cache_date',
  GAME_TOKEN = 'game_token',
  FcmSuccessFullySaved = 'fcm_successfully_saved',
}
